### ISSUE TITLE
[Bug]: Devtool theme is wrong

### ISSUE THREAD

**Issue by SARDONYX-sard** [SARDONYX-sard/dar-to-oar#73]
### Version

0.8.1

### Unexpected behavior here

Windows 11 Home  23H2
I assume it is a bug in the OS Webview itself, as it has been the same in past versions.

https://github.com/tauri-apps/tauri/issues/10629

### Expected behavior

.

**Comment by SARDONYX-sard** [comment]
`Microsoft.EdgeWebView2Runtime 130.0.2849.46` does not seem to turn white if you uncheck `Match Microsoft Edge colour scheme` and use `Dark+` as with Edge.

However, if you use other Dark themes, some of them are white, and they are not very easy to use until now.

**Comment by S1lander** [comment]
> `Microsoft.EdgeWebView2Runtime 130.0.2849.46` does not seem to turn white if you uncheck `Match Microsoft Edge colour scheme` and use `Dark+` as with Edge.
> 
> However, if you use other Dark themes, some of them are white, and they are not very easy to use until now.

Finally a solution for this annoying problem, THANK YOU!
Summary:

1. Open Settings
2. Uncheck `Match Microsoft Edge color scheme`
3. Set `Theme` to `Dark+ (Default)`
